### ISSUE TITLE
Persist Authentication issue

### ISSUE THREAD

**Issue by ssack** [auth0-blog/ngrx-auth#4]
Good morning, im currently having an issue with persisting authentication on refresh. I was wondering if you could help me.. Here is my checkLogin$ effect:

@Effect()
  checkLogin$ = this.actions$.pipe(
    ofType(fromAuth.AuthActionTypes.CheckLogin),
    exhaustMap(() => {
      console.debug('IN CHECKLOGIN$');
      console.debug(`CHECKLOGIN$:: ${this.authService.authenticated}`);
      if (this.authService.authenticated) {
        return this.authService.checkSession$().pipe(
          map((authResult: any) => {            
            if (authResult && authResult.accessToken) {
              this.authService.setAuth(authResult);
              return new fromAuth.LoginSuccess();
            }
          }),
          catchError(error => {
            this.authService.resetAuthFlag();
            return of( new fromAuth.LoginFailure({ error }));
          })
        );
      } else {
        return EMPTY;
      }
    })
  );

Sorry: The issue i'm having is the console.debugs are never hit. 

Im receiving an error message when it tries to call the checksession$(): the cb parameter is invalid..

Thank you in advance

**Comment by samjulien** [comment]
Hey there, sorry I missed this. Are you still having this problem? Are you defining `checkSession$` as `checkSession$ = bindNodeCallback(this._Auth0.checkSession.bind(this._Auth0));` in the auth service?
